spring:
  application:
    name: post-demo
  profiles:
    active: dev
    # ?? swagger3
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
  # todo ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/post_demo
    username: root
    password: "000000"
server:
  port: 8101
  servlet:
    context-path: /api
sa-token:
  # token ??????? cookie ???
  token-name: satoken
  # token ????????? ??3 ??-1 ??????
  timeout: 259200
  # token ??????????????? token ???????????????????-1 ??????????
  active-timeout: -1
  # ?????????????? ?? true ???????, ? false ??????????
  is-concurrent: true
  # ????????????????? token ?? true ????????? token, ? false ????????? token?
  is-share: true
  # token ?????????uuid?simple-uuid?random-32?random-64?random-128?tik?
  token-style: uuid
  is-log: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0